version: "3.8"
services:
  simplewebapp:
    image: simple
    build:
     context: .
    ports:
    - "8080:8080"

  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgresql'